# Generated by Django 5.2.17 on 2026-08-14 06:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='The date of the gratitude entry (YYYY-MM-DD)')),
                ('content', models.TextField(help_text='A paragraph expressing daily gratitude and reflection')),
                ('mood', models.CharField(blank=True, choices=[('grateful', '🙏 Grateful'), ('joyful', '✨ Joyful'), ('peaceful', '🌿 Peaceful'), ('energized', '⚡ Energized'), ('reflective', '💭 Reflective'), ('hopeful', '🌅 Hopeful')], default='grateful', max_length=30)),
                ('prompt_answered', models.CharField(blank=True, default='', help_text='Optional prompt used for inspiration', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who authored this journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gratitude Entry',
                'verbose_name_plural': 'Gratitude Entries',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('owner', 'date')},
            },
        ),
    ]
